name: Publish CI
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: pnpm
      - name: Install
        run: |
          npm install -g pnpm
          pnpm
        env:
          CI: "true"
      - name: Build
        run: |
          pnpm build
        env:
          CI: "true"
      - name: Check Circular Dependencies
        run: |
          pnpm circular
        env:
          CI: "true"
      - name: Test
        run: |
          pnpm test --run --coverage
        env:
          CI: "true"
      - name: Examples
        run: |
          cd packages/pnpm-ts-monorepo
          node build/examples/main.js
        env:
          CI: "true"
